[toolchain]

[features]
resolution = true
skip-lint = false

[registry]
url = "http://localhost:8899"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

